In [1]:
import numpy as np
import pandas as pd
import os

In [6]:
df1 = pd.read_csv("C:/Users/709-000/Desktop/새 폴더/서울시 상권분석 데이터/서울시 우리마을가게 상권분석서비스(상권영역).csv")
df1

,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,엑스좌표_값,와이좌표_값,시군구_코드,행정동_코드,형태정보,기준_년월_코드
0,R,전통시장,1001475,강남개포시장,206065,443310,11680,11680670,NaN,201810
1,R,전통시장,1001412,화곡본동시장,186203,449328,11500,11500590,NaN,201810
2,R,전통시장,1001413,까치산시장,186493,448134,11500,11500593,NaN,201810
3,R,전통시장,1001414,송화골목시장,185468,449994,11500,11500611,NaN,201810
4,R,전통시장,1001452,중부시장,196125,442779,11620,11620575,NaN,201810
5,R,전통시장,1001415,방신전통시장,183436,452447,11500,11500630,NaN,201810
6,R,전통시장,1001416,공항시장,183061,451453,11500,11500640,NaN,201810
7,R,전통시장,1001423,독산동 우시장,190850,440835,11545,11545610,NaN,201810
8,R,전통시장,1001424,남문시장,191252,441586,11545,11545630,NaN,201810
9,R,전통시장,1001425,푸른터시장,191280,442074,11545,11545630,NaN,201810
10,R,전통시장,1001426,대명시장,191352,439419,11545,11545670,NaN,201810
11,R,전통시장,1001427,현대시장,191405,439748,11545,11545670,NaN,201810
12,R,전통시장,1001428,박미시장,191603,437870,11545,11545690,NaN,201810
13,R,전통시장,1001429,은행나무시장,191997,439104,11545,11545710,NaN,201810
14,R,전통시장,1001470,강남시장_강남,201829,446589,11680,11680510,NaN,201810
15,R,전통시장,1001372,녹번시장,193917,455718,11380,11380580,NaN,201810
16,R,전통시장,1001373,신응암시장,192811,454967,11380,11380590,NaN,201810
17,R,전통시장,1001374,대림골목시장,192695,454174,11380,11380600,NaN,201810
18,R,전통시장,1001480,새마을시장,207504,445512,11710,11710650,NaN,201810
19,R,전통시장,1001440,노량진중앙시장,195108,445854,11590,11590510,NaN,201810
20,R,전통시장,1001441,본동인정시장,195635,445813,11590,11590510,NaN,201810
21,R,전통시장,1001442,신노량진시장,194668,445449,11590,11590520,NaN,201810
22,R,전통시장,1001443,강남시장_동작,195878,444164,11590,11590530,NaN,201810
23,R,전통시장,1001444,상도전통시장,195766,444412,11590,11590530,NaN,201810
24,R,전통시장,1001445,영도시장,194738,444982,11590,11590540,NaN,201810
25,R,전통시장,1001446,성대시장,193926,444480,11590,11590550,NaN,201810
26,R,전통시장,1001375,증산종합시장,191630,453574,11380,11380640,NaN,201810
27,R,전통시장,1001376,수일시장,190738,453732,11380,11380650,NaN,201810
28,R,전통시장,1001460,관악신사시장,192646,442975,11620,11620685,NaN,201810
29,R,전통시장,1001461,신림종합시장,192665,442804,11620,11620685,NaN,201810
...,...,...,...,...,...,...,...,...,...,...
1466,R,전통시장,1001454,봉천제일종합시장,195147,442413,11620,11620595,NaN,201810
1467,R,전통시장,1001474,도곡시장,204551,444227,11680,11680650,NaN,201810
1468,D,발달상권,1001059,교대역_3,201065,443865,11650,11650530,NaN,201810
1469,D,발달상권,1001060,가락시장,210036,443852,11710,11710631,NaN,201810
1470,D,발달상권,1001061,방배동카페골목,198796,443913,11650,11650590,NaN,201810
1471,D,발달상권,1001062,서울 강남구 강남역_1,202416,443988,11650,11650520,NaN,201810
1472,D,발달상권,1001181,서울 광진구 군자역,206935,450796,11215,11215730,NaN,201810
1473,D,발달상권,1001123,학동사거리_1,203226,446892,11680,11680531,NaN,201810
1474,R,전통시장,1001490,길동복조리시장,212698,448781,11740,11740685,NaN,201810
1475,R,전통시장,1001332,사가정시장,207989,453527,11260,11260575,NaN,201810
1476,R,전통시장,1001333,중화제일시장,206662,456140,11260,11260630,NaN,201810
1477,R,전통시장,1001334,태능시장,206759,455413,11260,11260610,NaN,201810
1478,R,전통시장,1001335,묵1동도깨비시장,207147,457479,11260,11260620,NaN,201810
1479,R,전통시장,1001336,우림골목시장,208659,455348,11260,11260655,NaN,201810
1480,R,전통시장,1001337,유영시장,208553,454672,11260,11260660,NaN,201810
1481,R,전통시장,1001338,돈암제일시장,201402,454703,11290,11290555,NaN,201810
1482,R,전통시장,1001377,영천시장,196581,452325,11410,11410520,NaN,201810
1483,A,골목상권,1000379,동일로173가길,206395,458052,11350,11350595,NaN,201810
1484,A,골목상권,1000380,동일로192길,206671,458471,11350,11350595,NaN,201810
1485,A,골목상권,1000381,동일로242길,205175,463916,11350,11350630,NaN,201810
1486,A,골목상권,1000071,이태원로54길,200121,448560,11170,11170685,NaN,201810
1487,A,골목상권,1000072,장문로45길,200041,447690,11170,11170700,NaN,201810
1488,A,골목상권,1000073,청파로47길,197165,449449,11170,11170555,NaN,201810
1489,D,발달상권,1001042,서울 서초구 남부터미널역_3,201432,443037,11650,11650510,NaN,201810
1490,D,발달상권,1001043,동작구 총신대입구역_2,198499,442941,11650,11650621,NaN,201810
1491,D,발달상권,1001044,양재역_3,202755,443008,11650,11650520,NaN,201810
1492,D,발달상권,1001030,양재역_2,203216,442691,11650,11650651,NaN,201810
1493,D,발달상권,1001031,서울 관악구 신림역_1,193706,442615,11620,11620645,NaN,201810
1494,D,발달상권,1001032,서울 관악구 신림역_2,193880,442602,11620,11620645,NaN,201810
1495,D,발달상권,1001033,서울 서초구 남부터미널역_1,201661,442764,11650,11650510,NaN,201810

In [7]:
df1.columns

Index(['상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명', '엑스좌표_값', '와이좌표_값',
       '시군구_코드', '행정동_코드', '형태정보', '기준_년월_코드'],
      dtype='object')

In [37]:
df1.groupby('trdar_cd').mean()

          Unnamed: 0  stdr_yy_cd  stdr_qu_cd  tot_flpop_co       code
trdar_cd
1000001      26080.5      2018.0         2.5     181174.00  1000001.0
1000002      26081.5      2018.0         2.5     261543.75  1000002.0
1000003      26082.5      2018.0         2.5     134808.75  1000003.0
1000004      26083.5      2018.0         2.5     349808.75  1000004.0
1000005      26084.5      2018.0         2.5      32022.00  1000005.0
1000006      26085.5      2018.0         2.5      67089.00  1000006.0
1000007      26086.5      2018.0         2.5      58997.50  1000007.0
1000008      26087.5      2018.0         2.5      32681.25  1000008.0
1000009      26088.5      2018.0         2.5      32266.75  1000009.0
1000010      26089.5      2018.0         2.5     254794.25  1000010.0
1000011      26090.5      2018.0         2.5      97681.00  1000011.0
1000012      26091.5      2018.0         2.5     151272.00  1000012.0
1000013      26092.5      2018.0         2.5      80523.00  1000013.0
1000014      26093.5      2018.0         2.5      87553.25  1000014.0
1000015      26094.5      2018.0         2.5     186540.25  1000015.0
1000016      26095.5      2018.0         2.5     184994.25  1000016.0
1000017      26096.5      2018.0         2.5     101678.75  1000017.0
1000018      26097.5      2018.0         2.5     238008.75  1000018.0
1000019      26098.5      2018.0         2.5     262418.00  1000019.0
1000020      26099.5      2018.0         2.5     328897.75  1000020.0
1000021      26100.5      2018.0         2.5     118330.50  1000021.0
1000022      26101.5      2018.0         2.5      86030.50  1000022.0
1000023      26102.5      2018.0         2.5     221327.75  1000023.0
1000024      26103.5      2018.0         2.5     247285.50  1000024.0
1000025      26104.5      2018.0         2.5     191274.50  1000025.0
1000026      26105.5      2018.0         2.5       7491.50  1000026.0
1000027      26106.5      2018.0         2.5      58117.50  1000027.0
1000028      26107.5      2018.0         2.5     409832.50  1000028.0
1000029      26108.5      2018.0         2.5     140385.25  1000029.0
1000030      26109.5      2018.0         2.5     345343.00  1000030.0
...              ...         ...         ...           ...        ...
1001467      27545.5      2018.0         2.5       8796.50  1001467.0
1001468      27546.5      2018.0         2.5      12519.75  1001468.0
1001469      27547.5      2018.0         2.5      33575.50  1001469.0
1001470      27548.5      2018.0         2.5      73735.75  1001470.0
1001471      27549.5      2018.0         2.5     270265.75  1001471.0
1001472      27550.5      2018.0         2.5      20868.75  1001472.0
1001473      27551.5      2018.0         2.5      16375.00  1001473.0
1001474      27552.5      2018.0         2.5      58306.25  1001474.0
1001475      27553.5      2018.0         2.5      11994.75  1001475.0
1001476      27554.5      2018.0         2.5     129204.25  1001476.0
1001477      27555.5      2018.0         2.5      62480.50  1001477.0
1001478      27556.5      2018.0         2.5     217527.75  1001478.0
1001479      27557.5      2018.0         2.5      36263.00  1001479.0
1001480      27558.5      2018.0         2.5     298264.00  1001480.0
1001481      27559.5      2018.0         2.5      65557.00  1001481.0
1001482      27560.5      2018.0         2.5       9766.00  1001482.0
1001483      27561.5      2018.0         2.5     274572.50  1001483.0
1001484      27562.5      2018.0         2.5      36120.50  1001484.0
1001485      27563.5      2018.0         2.5      30213.25  1001485.0
1001486      27564.5      2018.0         2.5      30771.75  1001486.0
1001487      27565.5      2018.0         2.5     108196.75  1001487.0
1001488      27566.5      2018.0         2.5      93316.25  1001488.0
1001489      27567.5      2018.0         2.5      91589.25  1001489.0
1001490      27568.5      2018.0         2.5     212429.75  1001490.0
1001491      27569.5      2018.0         2.5    2480678.25  1001491.0
1001492      27570.5      2018.0         2.5    6194858.75  1001492.0
1001493      27571.5      2018.0         2.5    2844016.00  1001493.0
1001494      27572.5      2018.0         2.5    5328049.75  1001494.0
1001495      27573.5      2018.0         2.5    2007006.75  1001495.0
1001496      27574.5      2018.0         2.5      51596.25  1001496.0

[1495 rows x 5 columns]

In [49]:
df1.unstack

<bound method DataFrame.unstack of       Unnamed: 0  stdr_yy_cd  stdr_qu_cd trdar_se_cd trdar_se_cd_nm  trdar_cd  \
0          23838        2018           1           A           골목상권   1000001
1          23839        2018           1           A           골목상권   1000002
2          23840        2018           1           A           골목상권   1000003
3          23841        2018           1           A           골목상권   1000004
4          23842        2018           1           A           골목상권   1000005
5          23843        2018           1           A           골목상권   1000006
6          23844        2018           1           A           골목상권   1000007
7          23845        2018           1           A           골목상권   1000008
8          23846        2018           1           A           골목상권   1000009
9          23847        2018           1           A           골목상권   1000010
10         23848        2018           1           A           골목상권   1000011
11         23849        2018           1           A           골목상권   1000012
12         23850        2018           1           A           골목상권   1000013
13         23851        2018           1           A           골목상권   1000014
14         23852        2018           1           A           골목상권   1000015
15         23853        2018           1           A           골목상권   1000016
16         23854        2018           1           A           골목상권   1000017
17         23855        2018           1           A           골목상권   1000018
18         23856        2018           1           A           골목상권   1000019
19         23857        2018           1           A           골목상권   1000020
20         23858        2018           1           A           골목상권   1000021
21         23859        2018           1           A           골목상권   1000022
22         23860        2018           1           A           골목상권   1000023
23         23861        2018           1           A           골목상권   1000024
24         23862        2018           1           A           골목상권   1000025
25         23863        2018           1           A           골목상권   1000026
26         23864        2018           1           A           골목상권   1000027
27         23865        2018           1           A           골목상권   1000028
28         23866        2018           1           A           골목상권   1000029
29         23867        2018           1           A           골목상권   1000030
...          ...         ...         ...         ...            ...       ...
5950       29788        2018           4           R           전통시장   1001467
5951       29789        2018           4           R           전통시장   1001468
5952       29790        2018           4           R           전통시장   1001469
5953       29791        2018           4           R           전통시장   1001470
5954       29792        2018           4           R           전통시장   1001471
5955       29793        2018           4           R           전통시장   1001472
5956       29794        2018           4           R           전통시장   1001473
5957       29795        2018           4           R           전통시장   1001474
5958       29796        2018           4           R           전통시장   1001475
5959       29797        2018           4           R           전통시장   1001476
5960       29798        2018           4           R           전통시장   1001477
5961       29799        2018           4           R           전통시장   1001478
5962       29800        2018           4           R           전통시장   1001479
5963       29801        2018           4           R           전통시장   1001480
5964       29802        2018           4           R           전통시장   1001481
5965       29803        2018           4           R           전통시장   1001482
5966       29804        2018           4           R           전통시장   1001483
5967       29805        2018           4           R           전통시장   1001484
5968       29806        2018           4           R           전통시장   1001485
5969       29807        2018           4           R           전통시장   1001486
5970       29808        2018           4           R           전통시장   1001487
5971       29809        2018           4           R           전통시장   1001488
5972       29810        2018           4           R           전통시장   1001489
5973       29811        2018           4           R           전통시장   1001490
5974       29812        2018           4           U           관광특구   1001491
5975       29813        2018           4           U           관광특구   1001492
5976       29814        2018           4           U           관광특구   1001493
5977       29815        2018           4           U           관광특구   1001494
5978       29816        2018           4           U           관광특구   1001495
5979       29817        2018           4           U           관광특구   1001496

                 trdar_cd_nm  tot_flpop_co     code
0                        계동길        188508  1000001
1                     난계로27길        221016  1000002
2                   돈화문로11가길        126611  1000003
3                        명륜길        333306  1000004
4                       백석동길         24734  1000005
5                     북촌로11길         58697  1000006
6                      북촌로5길         30330  1000007
7                     북촌로5나길         31363  1000008
8                      삼청로5길         21795  1000009
9                     성균관로5길        220842  1000010
10                      숭인동길         92858  1000011
11                       옥인길        200528  1000012
12                    율곡로10길         78326  1000013
13                    율곡로16길         69147  1000014
14                      이화장길        163770  1000015
15                    자하문로7길        160663  1000016
16                     종로24길        101627  1000017
17                    종로58가길        215208  1000018
18                     종로65길        253305  1000019
19                     지봉로8길        298479  1000020
20                   창경궁로35길        114064  1000021
21                      창신2길         86034  1000022
22                      창신5길        204276  1000023
23                       창신길        197877  1000024
24                    통일로12길        380865  1000025
25                       평창길         19242  1000026
26                    필운대로1길         75114  1000027
27                    난계로11길        411508  1000028
28                    난계로21길        137580  1000029
29                    다산로33길        343628  1000030
...                      ...           ...      ...
5950                    우림시장          8715  1001467
5951                  남부종합시장         12537  1001468
5952                    양재시장         24622  1001469
5953                 강남시장_강남         74422  1001470
5954                  영동전통시장        274931  1001471
5955                  논현종합시장         23840  1001472
5956                  청담삼익시장         18151  1001473
5957                    도곡시장         56883  1001474
5958                  강남개포시장         11380  1001475
5959                    풍납시장        124411  1001476
5960                    마천시장         57728  1001477
5961                    방이시장        223264  1001478
5962                    석촌시장         49250  1001479
5963                   새마을시장        302031  1001480
5964                  명일골목시장         46226  1001481
5965                  고덕전통시장          7551  1001482
5966                  암사종합시장        283505  1001483
5967                  양지골목시장         41500  1001484
5968                고분다리골목시장         28872  1001485
5969                   동서울시장         35634  1001486
5970                    천호시장        123897  1001487
5971                  성내골목시장         91097  1001488
5972                 둔촌역전통시장        133660  1001489
5973                 길동복조리시장        207466  1001490
5974                이태원 관광특구       2345615  1001491
5975  명동 남대문 북창동 다동 무교동 관광특구       4905600  1001492
5976            동대문패션타운 관광특구       2757199  1001493
5977              종로·청계 관광특구       4524906  1001494
5978                 잠실 관광특구       1912079  1001495
5979             강남 마이스 관광특구         56902  1001496

[5980 rows x 9 columns]>

In [ ]:
df1['trdar_cd'] = df1.B.map(df.A)